name: Pipeline CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4
      
      - name: Verificando arquivos
        run: ls -la
    
    
